hyperparameters:
  lr: 3e-5
  hl_gauss: false
  reverse_kl: true # previous default "false"
  actor_kl_clip_mode: "full" # "full", "clipped", "kl_relu_clipped", "kl_bound_clipped", "value"
  ## entropy settings