# @package _global_

defaults:
  - env: mjx_dmc
  - architecture: old
  - overrides: default
  - _self_

hyperparameters:
    lr: 3e-4
    gamma: 0.99
    lmbda: 0.95
    clip_ratio: 0.2
    value_coef: 0.5
    entropy_coef: 0.002
    total_time_steps: 50_000_000
    num_steps: 64
    num_mini_batches: 32
    num_envs: 2048
    num_epochs: 16
    max_grad_norm: 0.5
    normalize_advantages: True
    normalize_env: True
    anneal_lr: False
    normalize_rewards: False
    reward_norm_epsilon: 1e-8
    reward_norm_clip: 10.0
    adaptive_lr: False
    desired_kl: 0.01
    adaptive_lr_factor: 1.5
    adaptive_lr_min: 1e-5
    adaptive_lr_max: 1e-2
    use_reppo_actor_policy: false
    use_reppo_value_function: false
    actor_hidden_dim: 512
    num_actor_layers: 3
    use_actor_norm: true
    use_actor_skip: false
    actor_min_std: 0.0
    critic_hidden_dim: 512
    num_critic_head_layers: 2
    use_critic_norm: true
    use_critic_skip: false
    num_eval: 20
    max_episode_steps: 1000
name: "ppo"
tags: ["ppo_baseline_retuned"]
seed: 0
num_seeds: 1
tune: false
checkpoint_dir: null
trials: 1
wandb:
  mode: "online" # set to online to activate wandb
  entity: ""
  project: "dime_${env.name}"
  project_suffix: ""
