# @package _global_

# With the change from Horeka in 2024, that single GPUs can be allocated, this simplifies the configuration and should
# allow faster queueing times. This configuration is for a single GPU on Horeka.

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN  # needed for launcher to be used
  launcher:
    # launcher/cluster specific options
    partition: "accelerated,accelerated-h100"
    timeout_min: 1080 # in minutes
    gres: gpu:1
    exclude: hkn0635,hkn0417,hkn0612
    mem_per_gpu: 125400  # in MB
    # exclude: node[4-5]  # e.g. do not allocate on these nodes because the RTX2080 doesn't have enough VRAM
    additional_parameters:
      cpus-per-task: 16  # maybe more?
      account: hk-project-p0022232
    setup:
      # Create wandb folder in fast, job-local storage: https://www.nhr.kit.edu/userdocs/horeka/filesystems/#tmpdir
      # NOTE: wandb folder will be deleted after job completion, but by then it will have synced with server
      - export WANDB_DIR=$TMPDIR/wandb
      - mkdir -pv $WANDB_DIR
      - export WANDB_CONSOLE=off


