# @package _global_
defaults:
  - override /hydra/launcher: clusterduck_slurm


hydra:
  mode: MULTIRUN  # needed for launcher to be used
  launcher:
    # launcher/cluster specific options
    timeout_min: 600
    partition: accelerated,accelerated-h100
#    partition: dev_accelerated
    gres: gpu:1
    exclude: hkn0635,hkn0417
    additional_parameters:
      # cpus-per-task: 38
      account: hk-project-p0022232
    setup:
      # Create wandb folder in fast, job-local storage: https://www.nhr.kit.edu/userdocs/horeka/filesystems/#tmpdir
      # NOTE: wandb folder will be deleted after job completion, but by then it will have synced with server
      - export WANDB_DIR=$TMPDIR/wandb
      - mkdir -pv $WANDB_DIR
      - export WANDB_CONSOLE=off
      - echo "MUJOCO_EGL_DEVICE_ID=$MUJOCO_EGL_DEVICE_ID"
      - export MUJOCO_EGL_DEVICE_ID=0

    # clusterduck specific options
    parallel_runs_per_node: 1
    total_runs_per_node: 1  # optional. None puts all runs into one slurm job
    resources_config:
      cpu:
      # cuda:
      # rendering:
      stagger:
        delay: 5

  # disable logging from job to stdout, as this pollutes slurm output
  job_logging:
    root:
      handlers: [file]
