hyperparameters: 
  anneal_lr: false

  #lr_decay_factor: 0.05
  #lr: 3e-5
  #hl_gauss: true
  #reverse_kl: false # previous default "false"
  #actor_kl_clip_mode: "clipped" # "full", "clipped", "kl_relu_clipped", "kl_bound_clipped", "value"
  #ent_target_mult: 4
  #num_bins: 302
  ## entropy settings